### ISSUE TITLE
Implement back Solder (stack of 10) foundry Recipe

### ISSUE THREAD

**Issue by Chaoschaot232** [brevven/tin#6]
With Aluminium plate and Tin plate you are going to create Solder which is fine but why was the satcked recipe removed? There was no reason for it.

It is much better and easier to use stacked and/or sacked and high-pressure recipes directly instead of stacking and unstacking stuff.

Here is the image of what happened and how it destroyed an important part of my base: https://i.imgur.com/XLEsVA1.jpeg

**Comment by brevven** [comment]
Hi, apologies for delay in this. I sometimes miss github issues. I'll take a look into this and fix it.

**Comment by brevven** [comment]
I'm currently able to created stacked solder in various loadouts. Let me know if you still are not able.
